generator/config.go

At Alpine Linux, Linux Kernel files are also located in /lib instead
of /usr/lib. For this reason, I patch the constants in config.go
accordingly for the Alpine Linux booster package. However, while working
on this I noticed that config.go does not re-use the imageModulesDir
constant. I think it makes sense to re-use it to not hardcode the path
twice.

generator: re-use imageModulesDir constant

---

generator/image.go

While creating a booster package for Alpine Linux, I noticed that
booster assumes unconditionally that shared libraries are located in
/usr/lib. Contrary to Arch Linux, Alpine uses both /usr/lib and /lib.
For example, the shared library for our musl libc is located in /lib.
This patch adds a workaround which checks /lib (in addition to /usr/lib)
for shared libraries, if the library wasn't found in the latter. A proper
solution would probably be not hardcoding any library directories at all
but this should be fine for now until the comment in `AppendElfDependencies`
is addressed:
https://github.com/anatol/booster/blob/82f015198b46c08f4216152044487760260edbd7/generator/image.go#L324-L325

image: add workaround to deal with libraries located in /lib

---

generator/generator.go

Otherwise, the symlinks may point to non-existend target directories
if we only install files from /bin and /lib. For example, on Alpine
BusyBox is located in /bin/busybox and hence the /usr/bin directory
is not created without this commit.

generator: when creating compatibility symlinks ensure target exists

---

generator/config.go
generator/console.go
generator/generator_test.go
generator/image.go
generator/kmod.go
generator/kmod_test.go
init/hwpath.go
init/module.go
init/udev.go
init/wwid.go
tests/util.go

The `path` pkg is only intended to be used for “paths separated by forward slashes”. Even though Booster only supports Linux and Linux only uses slash-separated paths I think it is still cleaner to always use `path/filepath` over `path` for operating system file paths. As such, this is only a very small refactoring and (hopefully) shouldn't cause any functional changes.
I only noticed this because some files (e.g. `generator/image.go`) import both `path` as well as `path/filepath` but seem to use path for operating system paths.

Always use path/filepath pkg for operating systems paths

---

generator/console.go
generator/generator.go

This allows modifying their value via the `-X` flag provided by `go tool link`. This eases packaging of Booster as distributions which use different paths for these directories don't need to patch Booster but instead can set these variables using:
go build --ldflags="-X main.consolefontsDir=/foo/bar/…"

generator: Convert constants pointing to directory to variables

---

docs/manpage.md

Changed `--kernel-kersion` to `--kernel-version` in the examples, I dont think it needs any explaining.

Fix typo in example commands

---

init/cmdline.go
init/cmdline_test.go

For: https://github.com/anatol/booster/issues/73#issuecomment-1210899737
The parser is missing an edge case for quotes within values, which could be technically valid. This allows those conditions to pass successfully while keeping everything cleaned up as before. This is a very minimal modification to account for the condition. 
For now the error condition is reduced to allow quotes if they follow an equals sign. This allows the test case to work, but would still catch more unusual edge cases. If more conditions that need to allow quotes within sub-strings are needed the restriction on the quotes in values side can be removed to allow a better behavioral handle.
- Fixing parsing error that happens when quotes are deeper into values in key=value checks. IE: `key=UUID="test"`
- Update …

Fix parsing errors when quotes are inside values

---

docs/manpage.md
init/cmdline.go
init/luks.go
init/main.go

For #37: Add support to allow unlocking a luks volume by keyfile, reworked the luks mappings a little to allow more complex patterns of parsing parameters and building mappings.
This slightly tweaks creating luksMapping lists so they can occur multiple times in the kernel parameter list and it just updates the relevant properties for each mapping (to allow extending even further if desired).
- updated luksMapping type to hold a keyfile
- add a luksMapping findOrCreate function in luks.go, either finds the existing mapping by UUID or adds one
- update the rd.luks.uuid and rd.luks.name in cmdline.go to make use of findOrCreate 
- adds rd.luks.key with the format UUID=keyfile which should point to a file in initramfs containing the password
- adds recoverKeyfilePassword go routine which …

ISSUE-37: Allow luks unlocking via keyfile specified in kernel parameters with rd.luks.key

---

init/blkinfo_test.go

When trying to diagnose https://github.com/anatol/booster/issues/172, I had (admittedly, not very much) trouble discerning which assertion was actually failing in `TestBlkInfo`. To this end, I propose splitting this test into multiple tests, allowing problems to be highlighted more easily, and adhering to the general maxim that only one logical component should be included per test.

Split blkinfo test into multiple tests

---

generator/generator_test.go

In `TestExtraFiles` in `generator_test.go`, a `stat` check was being performed twice --- once inside the `for` loop and then again afterwards with calls to `checkFileExistence`. Have deleted the latter checks and converted the check inside the `for` loop to a call to `checkFIleExistence`. Also converted string concatenation of paths to calls to `filepath.Join`.

Deduplicated check in TestExtraFiles

---

docs/manpage.md
init/cmdline.go

init: allow force loading of extra modules via the kernel command-line

---

generator/kmod.go
init/udev.go

From `modprobe.d(5)`:
> Note that module and alias names (like other module names) can have - or _ in them: both are interchangeable throughout all the module commands as underscore conversion happens automatically.
For this reason, we need to make sure that everywhere where module or pattern names are compared that this comparison is always performed on a normalized string. This commit adds several normalizations for module and pattern names that were previously not performed.
Fixes #185

generator: normalize both module and pattern names from modules.alias

---

README.md

Booster has been in the [official Alpine community repository](https://pkgs.alpinelinux.org/package/edge/community/x86_64/booster) and can nowadays be used to replace Alpine's default [mkinitfs](https://pkgs.alpinelinux.org/package/edge/community/x86_64/booster) generator, hence I thought it may be worthwhile to also document Alpine installation instructions in the README.

README.md: Add installation instructions for Alpine Linux

---

generator/generator.go

Nothing special here - just another extension to handle. While we're here, mentioning the kernel version which landed support is more beneficial to when it was by distribution X or Y - the project is aiming at multiple distributions after all.
Closes: https://github.com/anatol/booster/issues/224

Handle zstd compressed firmware

---

generator/generator.go

https://github.com/anatol/booster/issues/237

generator: force load usbhid and hid_sensor_hub

---

packaging/arch/booster-remove

Some users may delete booster images if they create UKI files.
Do not report removal errors if file does not exist.
mkinitcpio deletes files with the -f option:
https://github.com/archlinux/mkinitcpio/blob/ffae4b4821aa7d12271165cacf87d6772c70a8b4/libalpm/scripts/mkinitcpio#L115

packaging: arch: Do not report removal errors for nonexistent files

---

generator/generator.go
init/luks.go
init/udev.go

Accomplishes the same effect as https://github.com/anatol/booster/commit/1b655775edd015b0aa584a30f79c5d25ef8d5489 but instead of forcibly loading the `usbhid` and `hid_sensor_hub` modules, specific events are listened and waited for, namely, the `hid-generic` and the `usbhid` drivers. 
It appears booster is being too fast, and doesn't wait long enough for the  built in `hid-generic` driver to target the hidraw devices plugged via usb. As a result, errors occur for uevents when attempting to recover the fido2 password from hidraw devices.
This way unlocking encrypted partitions with fido2 keys is possible by only specifying `fido2-assert` in booster.yaml, but without the workarounds of generating a universal image and loading the `hid_sensor_hub`.

init: wait for usbhid drivers for fido2 unlocking

---

docs/manpage.md

I've added a small a paragraph to the debugging section of the documentation. It may help people getting the boot logs from busybox.

Documentation, debugging

---

generator/image.go

Hi,
I've recently been trying to packaging booster for my debian/ubuntu based distro and we ran into an issue with the elfLibDir not having the path debian uses. This PR fixes that.

Add debian lib64 path to elfLibDir

---

docs/manpage.md
packaging/arch/PKGBUILD
packaging/arch/regenerate_uki

Currently, booster does not support generating [Universal Kernel Images](https://uapi-group.org/specifications/specs/unified_kernel_image/) (UKIs) natively and this PR allows creating UKIs via ukify on Arch Linux. 
To generate UKIs, we can simply delegate the functionality to external tools such as ukify. The resulting binaries are currently stored in `/boot/Linux/EFI` and manual intervention would be required from the user to configure the appropriate boot loader configution files to load the binary by default. Otherwise, binaries would probably need to be selected at boot time. For instance, in systemd-boot, `loader.conf` should be modified.

arch: add script to generate UKIs

---

packaging/arch/PKGBUILD

Even though systemd-ukify was added to optional package dependencies and the regenerate_uki script was provided - it was not included in the final package.

Add regenerate_uki script to Arch packaging

---

init/luks.go

this checks the Usage Page value from report_descriptor against 0xd0f1, similar to how it's done in libfido2
references:
- https://github.com/Yubico/libfido2/blob/03c18d396eb209a42bbf62f5f4415203cba2fc50/src/hid_hidapi.c#L146
- https://www.usb.org/sites/default/files/hid1_11.pdf 6.2.2.7 Global Item
tested with pico-fido

init: check hidraw descriptor to figure out fido or not

---

init/wwid.go

File descriptors to block devices (like /dev/sda) currently remain open and are inherited down the userspace process tree through PID 1. For example, on my machine the LVM command `vgchange` issues this warning during system initialization:
```
File descriptor 6 (/dev/sda) leaked on vgchange invocation.
```
This change closes the file descriptors properly, eliminating those warnings from the boot messages.

Bugfix: close device file descriptors in wwid
